
version: '3.1'
services:
  tareas-dev:
    entrypoint: yarn run dev
    hostname: uae_simulacion-tareas-dev
    image: node:20
    user: "1000:1000"
    volumes:
      - ./uae-tareas-simulacion:/App
    working_dir: /App
  tareas-produccion:
    build: ./uae-tareas-simulacion
    entrypoint: yarn run start
    hostname: uae_simulacion-tareas-produccion
    image: uae_simulacion/tareas-produccion:0.1
    networks:
      - https-proxy
    user: "1000:1000"
    restart: unless-stopped
    working_dir: /App
networks:
  https-proxy: 
    external: true

