import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const SIMULADORES = [
    {
      abreviatura: "ACM",
      titulo: "Algoritmo Congruencial Multiplicativo",
      url: "/20221106-1-algorirmo-congruencial-multiplicativo/",
    },
    {
      abreviatura: "MTI",
      titulo: "Método de Transformación Inversa",
      url: "/20221106-1-algorirmo-congruencial-multiplicativo/",
    },
    {
      abreviatura: "Distribución Binomial",
      titulo: "Simulador Distribución Binomial",
      url: "/20221219-2-simulador-distribucion-binomial/",
    },
  ]

  return (
    <div className={styles.container}>
      <Head>
        <title>Simuladores de Probabilidad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Learn <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <div className={styles.grid}>
          {SIMULADORES.map(link => (
            <a kay={link.url} href={link.url} className={styles.card}>
              <h2>{link.abreviatura} &rarr;</h2>
              <p>{link.titulo}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
