import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home() {
  const SIMULADORES = [
    {
      abreviatura: "A. C. M.",
      titulo: "Algoritmo Congruencial Multiplicativo",
      url: "/algorirmo-congruencial-multiplicativo/",
    },
    {
      abreviatura: "M. T. I.",
      titulo: "Método de Transformación Inversa",
      url: "/metodo-tranformacion-inversa/",
    },
    {
      abreviatura: "Dist. Binomial",
      titulo: "Simulador Distribución Binomial",
      url: "/simulador-distribucion-binomial/",
    },
    {
      abreviatura: "Dist. Poisson",
      titulo: "Simulador Distribución Poisson",
      url: "/dostribucion-poison/",
    },
    {
      abreviatura: "Dist. Geométrica",
      titulo: "Simulador Distribución Geométrica",
      url: "/simulador-distribucion-geometroca/",
    },
  ]

  return (
    <div className={styles.container}>
      <Head>
        <title>Simuladores de Probabilidad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Simuladores de Probabilidad
        </h1>
        <div className={styles.grid}>
          {SIMULADORES.map(link => (
            <a kay={link.url} href={link.url} className={styles.card}>
              <h2>{link.abreviatura} &rarr;</h2>
              <p>{link.titulo}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <p>
          Por Walter Anthony Celi Vaca<br />
          Ingeniería en Ciencias de la Computación<br />
          Universidad Agraria del Ecuador<br />
        </p>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
